export const USER_STATE_CHANGED = " USER_STATE_CHANGED";
export const USER_POSTS_STATE_CHANGED = " USER_POSTS_STATE_CHANGED";
export const USER_FOLLOWING_STATE_CHANGED = "USER_FOLLOWING_STATE_CHANGED";
export const USER_FOLLOWED_STATE_CHANGED = "USER_FOLLOWED_STATE_CHANGED";
export const USER_FOLLOWING_STATE_CLEARED = "USER_FOLLOWING_STATE_CLEARED";
export const USER_FOLLOWED_STATE_CLEARED = "USER_FOLLOWED_STATE_CLEARED";
export const USER_LOGOUT = "USER_LOGOUT";
